    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: elassandra-cl1-dc1-user-config
      labels:
        app: elassandra
        cluster: cl1 
        datacenter: dc1 
        parent: elassandra-cl1-dc1
    data:
      cassandra_yaml_d_user_config_overrides_yaml: |
        enable_materialized_views: true
      cassandra_yaml_d_user_config_overrides_yaml2: |
        enable_materialized_views: true
