#
# Copyright © 2016-2019 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: zookeeper:3.5
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 2181
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 2181
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888;0.0.0.0:2181"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
  - name: zk-port
    port: 2181
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-kafka
spec:
  template:
    metadata:
      labels:
        app: tb-kafka
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: wurstmeister/kafka:2.12-2.2.1
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 9092
        readinessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 9092
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "INSIDE://:9093,OUTSIDE://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://:9093,OUTSIDE://tb-kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_CREATE_TOPICS
          value: "js.eval.requests:100:1:delete --config=retention.ms=60000 --config=segment.bytes=26214400 --config=retention.bytes=104857600,tb.transport.api.requests:30:1:delete --config=retention.ms=60000 --config=segment.bytes=26214400 --config=retention.bytes=104857600,tb.rule-engine:30:1:delete --config=retention.ms=60000 --config=segment.bytes=26214400 --config=retention.bytes=104857600"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "1073741824"
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: "268435456"
        - name: KAFKA_LOG_RETENTION_MS
          value: "300000"
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: "delete"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tb-kafka
spec:
  type: ClusterIP
  selector:
    app: tb-kafka
  ports:
  - name: tb-kafka-port
    port: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-redis
spec:
  template:
    metadata:
      labels:
        app: tb-redis
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: redis:4.0
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 6379
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tb-redis
spec:
  type: ClusterIP
  selector:
    app: tb-redis
  ports:
  - name: tb-redis-port
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-js-executor
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tb-js-executor
  template:
    metadata:
      labels:
        app: tb-js-executor
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-js-executor:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        env:
        - name: REMOTE_JS_EVAL_REQUEST_TOPIC
          value: "js.eval.requests"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        - name: LOGGER_LEVEL
          value: "info"
        - name: LOG_FOLDER
          value: "logs"
        - name: LOGGER_FILENAME
          value: "tb-js-executor-%DATE%.log"
        - name: DOCKER_MODE
          value: "true"
        - name: SCRIPT_BODY_TRACE_FREQUENCY
          value: "1000"
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-node
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      volumes:
        - name: tb-node-config
          configMap:
            name: tb-node-config
            items:
              - key: conf
                path:  thingsboard.conf
              - key: logback
                path:  logback.xml
        - name: tbnode-ca-pub
          secret:
            secretName: ca-pub
            items:
              - key: cacert.pem
                path: cacert.pem
        - name: merged-cacerts
          emptyDir: {}
      initContainers:
      - name: merge-certificats
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-node:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        volumeMounts:
          - mountPath: /tmp/tbnode-truststore-to-import/
            name: tbnode-ca-pub
          - mountPath: /tmp/tbnode-truststore/
            name: merged-cacerts
        command: ['sh', '-c', 'cp  $JAVA_HOME/jre/lib/security/cacerts /tmp/tbnode-truststore/
        && keytool -import -trustcacerts -keystore /tmp/tbnode-truststore/cacerts -storepass changeit -noprompt -file /tmp/tbnode-truststore-to-import/cacert.pem ;']
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-node:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9001
          name: rpc
        env:
        - name: RPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZOOKEEPER_ENABLED
          value: "true"
        - name: ZOOKEEPER_URL
          value: "zookeeper:2181"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        - name: JS_EVALUATOR
          value: "remote"
        - name: TRANSPORT_TYPE
          value: "remote"
        - name: CACHE_TYPE
          value: "redis"
        - name: REDIS_HOST
          value: "tb-redis"
        - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
          value: "false"
        - name: REPORTS_SERVER_ENDPOINT_URL
          value: "https://tb-web-report.orchid.azure.strapcloud.com/"
        - name: CASSANDRA_USE_CREDENTIALS
          value: "true"
        - name: CASSANDRA_USE_SSL
          value: "true"
        - name: CASSANDRA_USERNAME
          value: "admin"
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              # make this name dynamic
              name: elassandra-orchid
              key: cassandra.admin_password
        - name: TB_LICENSE_SECRET
          valueFrom:
            secretKeyRef:
              name: tb-license-secret
              key: license-secret
        envFrom:
        - configMapRef:
            name: tb-node-db-config
        volumeMounts:
          - mountPath: /config
            name: tb-node-config
          - mountPath: /tmp/tbnode-truststore/
            name: merged-cacerts
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tb-node
spec:
  type: ClusterIP
  selector:
    app: tb-node
  ports:
  - port: 8080
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-mqtt-transport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-mqtt-transport
  template:
    metadata:
      labels:
        app: tb-mqtt-transport
    spec:
      volumes:
        - name: tb-mqtt-transport-config
          configMap:
            name: tb-mqtt-transport-config
            items:
            - key: conf
              path:  tb-mqtt-transport.conf
            - key: logback
              path:  logback.xml
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-mqtt-transport:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 1883
          name: mqtt
        env:
        - name: CLUSTER_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MQTT_BIND_ADDRESS
          value: "0.0.0.0"
        - name: MQTT_BIND_PORT
          value: "1883"
        - name: MQTT_TIMEOUT
          value: "10000"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        volumeMounts:
          - mountPath: /config
            name: tb-mqtt-transport-config
        readinessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 1883
        livenessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 1883
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-transport
spec:
  type: LoadBalancer
  selector:
    app: tb-mqtt-transport
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-http-transport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-http-transport
  template:
    metadata:
      labels:
        app: tb-http-transport
    spec:
      volumes:
        - name: tb-http-transport-config
          configMap:
            name: tb-http-transport-config
            items:
            - key: conf
              path:  tb-http-transport.conf
            - key: logback
              path:  logback.xml
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-http-transport:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CLUSTER_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HTTP_BIND_ADDRESS
          value: "0.0.0.0"
        - name: HTTP_BIND_PORT
          value: "8080"
        - name: HTTP_REQUEST_TIMEOUT
          value: "60000"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        volumeMounts:
          - mountPath: /config
            name: tb-http-transport-config
        readinessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 8080
        livenessProbe:
          periodSeconds: 20
          tcpSocket:
            port: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tb-http-transport
spec:
  type: ClusterIP
  selector:
    app: tb-http-transport
  ports:
  - port: 8080
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-web-ui
  template:
    metadata:
      labels:
        app: tb-web-ui
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: store/thingsboard/tb-pe-web-ui:2.4.3PE
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: HTTP_BIND_ADDRESS
          value: "0.0.0.0"
        - name: HTTP_BIND_PORT
          value: "8080"
        - name: TB_ENABLE_PROXY
          value: "false"
        - name: LOGGER_LEVEL
          value: "info"
        - name: LOG_FOLDER
          value: "logs"
        - name: LOGGER_FILENAME
          value: "tb-web-ui-%DATE%.log"
        - name: DOCKER_MODE
          value: "true"
        livenessProbe:
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tb-web-ui
spec:
  type: ClusterIP
  selector:
    app: tb-web-ui
  ports:
  - port: 8080
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tb-web-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tb-web-report
  template:
    metadata:
      labels:
        app: tb-web-report
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: store/thingsboard/tb-pe-web-report:2.4.3PE
          terminationMessagePolicy: "FallbackToLogsOnError"
          ports:
            - containerPort: 8383
              name: http
          env:
            - name: HTTP_BIND_ADDRESS
              value: "0.0.0.0"
            - name: HTTP_BIND_PORT
              value: "8383"
            - name: LOGGER_LEVEL
              value: "info"
            - name: LOG_FOLDER
              value: "logs"
            - name: LOGGER_FILENAME
              value: "tb-web-report-%DATE%.log"
            - name: DOCKER_MODE
              value: "true"
            - name: DEFAULT_PAGE_NAVIGATION_TIMEOUT
              value: "120000"
            - name: DASHBOARD_LOAD_WAIT_TIME
              value: "3000"
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 120
            timeoutSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service
metadata:
  name: tb-web-report
spec:
  type: ClusterIP
  selector:
    app: tb-web-report
  ports:
    - port: 8383
      name: http
---