    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: elassandra-testthingsboard-dc1-user-config
      labels:
        app: elassandra
        cluster: testthingsboard
        datacenter: dc1
        parent: elassandra-testthingsboard-dc1
    data:
      cassandra_yaml_d_user_config_overrides_yaml: |
        enable_materialized_views: true
      cassandra_yaml_d_user_config_overrides_yaml2: |
        enable_materialized_views: true
